### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by samarpan-rai** [samarpan-rai/healthchecks_wrapper#3]
StringIO in 2.7 requires writing in bytes whereas 3.7 requires in string. Therefore, the same code doesn't work for python 2.7.

**Comment by cuu508** [comment]
I would recommend to just drop Python 2.7 support. Python 2.7 reached its end-of-life 2 years ago, on January 2020. It is not receiving security updates any more.

**Comment by samarpan-rai** [comment]
> I would recommend to just drop Python 2.7 support. Python 2.7 reached its end-of-life 2 years ago, on January 2020. It is not receiving security updates any more.

Good point
