### ISSUE TITLE
Unused top_stack variable

### ISSUE THREAD

**Issue by cuu508** [samarpan-rai/healthchecks_wrapper#4]
* HealthChecks Context Manager version: 0.1.0
* Python version: 3.8
* Operating System: Ubuntu 20.04

### Description

I was reviewing the healthchecks_wrapper source code and noticed what looks like an unused code block:

```python
top_stack = StringIO()

top_lines = top_stack.getvalue().strip("\n").split("\n")[:-4]
top_stack.close()
```

Unless I'm missing something, this doesn't seem to do anything. Is there a reason it is there?

**Comment by samarpan-rai** [comment]
Yes, if you look further down it's used to format the message. The variable `top_lines` is later used to create the trace. 

```python
top_stack = StringIO()
top_lines = top_stack.getvalue().strip("\n").split("\n")[:-4]
top_stack.close()

full_stack = StringIO()
full_stack.write("Traceback (most recent call last):\n")
full_stack.write("\n".join(top_lines))
full_stack.write("\n")
```

**Comment by cuu508** [comment]
Where does top_stack's value come from, wouldn't it just be empty? (I
haven't run the code and may be missing something.)

**Comment by samarpan-rai** [comment]
Sorry for the super late reply. Got busy with the new job. I think you are partially right in your observation. The line doesn't add much value. I have removed it to actually add the full stack trace in the log when it fails.
